version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: capsule-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-capsule}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-capsule_dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-capsule_dev}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - capsule-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-capsule}']
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin - Database Management UI (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: capsule-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@capsule.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - capsule-network
    depends_on:
      - postgres
    profiles:
      - tools

  # Web Application (Development)
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: capsule-web
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-capsule}:${POSTGRES_PASSWORD:-capsule_dev_password}@postgres:5432/${POSTGRES_DB:-capsule_dev}
      NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - '${WEB_PORT:-3000}:3000'
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - capsule-network
    depends_on:
      postgres:
        condition: service_healthy
    command: pnpm dev --filter=web

volumes:
  postgres_data:
    name: capsule-postgres-data
  pgadmin_data:
    name: capsule-pgadmin-data

networks:
  capsule-network:
    name: capsule-network
    driver: bridge
